version: '3.8'

services:
  web:
    build: .
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - ./processed_images:/app/processed_images:rw
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  image_processor:
    build: .
    command: python /app/src/services/image_processor.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - redis

  saver:
    build: .
    command: python /app/src/services/mage_saver.py
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./processed_images:/app/processed_images:rw
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "${redis_port}:${redis_port}"

volumes:
  postgres_data:
